name: Build Ribosome Compiler

on:
  push:
    branches: [ alpha, main ]
  pull_request:
    branches: [ alpha, main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Download LLVM SDK
      run: |
        curl -LO https://github.com/vovkos/llvm-package-windows/releases/download/llvm-18.1.8/llvm-18.1.8-windows-amd64-msvc17-msvcrt.7z
      shell: cmd

    - name: Extract LLVM SDK
      run: |
        7z x llvm-18.1.8-windows-amd64-msvc17-msvcrt.7z -ollvm-sdk
      shell: cmd

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR="llvm-sdk/llvm-18.1.8-windows-amd64-msvc17-msvcrt/lib/cmake/llvm"
      shell: cmd

    - name: Build ribosome
      run: |
        cmake --build build --config Release
      shell: cmd
