name: Run Validation Tests

on:
  push:
    branches: [ alpha, main ]
  pull_request:
    branches: [ alpha, main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download LLVM SDK
      run: |
        curl -LO https://github.com/vovkos/llvm-package-windows/releases/download/llvm-18.1.8/llvm-18.1.8-windows-amd64-msvc17-msvcrt.7z
      shell: cmd

    - name: Extract LLVM SDK
      run: |
        7z x llvm-18.1.8-windows-amd64-msvc17-msvcrt.7z -ollvm-sdk
      shell: cmd

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DLLVM_DIR="llvm-sdk/llvm-18.1.8-windows-amd64-msvc17-msvcrt/lib/cmake/llvm"
      shell: cmd

    - name: Build compiler & runtime library
      run: |
        cmake --build build --config Release
      shell: cmd

    - name: Add LLVM DLLs to Path
      run: |
        echo %CD%\llvm-sdk\llvm-18.1.8-windows-amd64-msvc17-msvcrt\bin>> %GITHUB_PATH%
      shell: cmd

    - name: Run Test Suite
      run: |
        python tests/run_tests.py
      shell: cmd

    - name: Run Fuzzer Quick Check
      run: |
        python tests/fuzz_test.py --quick
      shell: cmd
